### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by azu** [azu/promises-book#248]
2.0.0に向けたメタIssueです。

- [x] getURLの変更 #310  
- [x] Promise#finllay #284 
- [x] AbortControllerへの言及 #259
- [x] Fetch APIについて #295
- [x] jQuery 3.0 #241
- [x] ECMAScript 2015+ => jsprimerへの言及で解決できそう(循環参照) #292 
  - 主にasync/awaitに向けての解説が欲しい #246 
  - ただしasync/awaitを説明するにはGeneratorの説明が必要なのが難しい
  - https://jsprimer.net/ もGeneratorを省いている #289
- [x] async/await #246 
- [ ] 逐次処理とAsync Generator #289
- [ ] ~EventとPromise~ #247
- [x] Unhandled Rejection #253 
- [ ] Promise.rejectとスタックトレース #287

## メタ

- [x] コードベースをES5 -> ES2015+にするべきかどうか? #249
- [x] httpsへの移行 or ドメイン or *.js.org #290 

マイルストーン: [2.0.0 Issues · azu/promises-book](https://github.com/azu/promises-book/milestones/2.0.0)

2.0.0にあった方が良さそうなものの意見募集中です

**Comment by azu** [comment]
async/awaitはES2017で入る

**Comment by azu** [comment]
jsprimer.net への言及で解決できる部分はあるけど、循環参照にならないように気をつけて実装しないといけない。
jsprimerからの言及は 非同期処理 のセクションのみに強く限定している。

**Comment by azu** [comment]
- [ ] Arrow Functionについての解説も追加
- [ ] Fetch APIについても解説を入れる

**Comment by azu** [comment]
- [ ] Node.jsのassert.rejectsについても追加する

**Comment by azu** [comment]
- [ ] https://azu.github.io/promises-book/archives/v1/ について触れる

**Comment by azu** [comment]
2.0予定のものはほぼ完了。

今後に備えてメンテナー増やしたいので、CONTRIBUTINGの拡充をする

**Comment by azu** [comment]
CONTRIBUTINGを追加した
